# site name
prefixName: Cx330
siteName: 2020
# favicon and site master avatar
favicon: /images/favicon.ico
url: https://github.com/ShmilyXI
avatar: /images/avatat2.jpg
description: 热爱可抵岁月漫长
cdn: https://cdn.jsdelivr.net/gh/ShmilyXI/Gallerys@master/BokeImage/
pjaxbackground/: 1
# 1开启
mathjax: 1

notice: 使用JS实现的数据结构及算法系列文章准备中...
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档:
    {
      path: /archives,
      fa: fa-archive faa-shake,
      submenus:
        {
          技术: { path: /categories/技术/, fa: fa-code },
          生活: { path: /categories/生活/, fa: fa-file-text-o },
          资源: { path: /categories/资源/, fa: fa-cloud-download },
          转载: { path: /categories/转载/, fa: fa-book },
        },
    }
  # 随想: {path: /categories/随想/, fa: fa-commenting-o },
  列表:
    {
      path: javascript:;,
      fa: fa-list-ul faa-vertical,
      submenus: { 书单: { path: /tags/书单/, fa: fa-th-list faa-bounce }, 图集: { path: /gallery/, fa: fa-photo }, 歌单: { path: /music/, fa: fa-headphones } },
    }
  # 番组: {path: /bangumi/, fa: fa-film faa-vertical },
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  # 友人帐: { path: /links/, fa: fa-link faa-shake }
  工坊: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: {
          Color: { path: /lover/, fa: fa-heart faa-pulse },
          Lab: { path: /lab/, fa: fa-cogs },
          # 云盘: { path: /netdisc/, fa: fa-cogs },
        } }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }

  # 关于: { path: /about/, fa: fa-leaf faa-wrench }
  # TODO:关于
  # 关于: { path: /, fa: fa-leaf faa-wrench , submenus: {
  #   我？: {path: /about/, fa: fa-meetup},
  #   主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
  #   Lab: {path: /lab/, fa: fa-cogs },
  # } }
  # 客户端: { path: /client/, fa: fa-android faa-vertical }
  # RSS: { path: /atom.xml, fa: fa-rss faa-pulse }

# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/ShmilyXI/Gallerys@master/NoteImage/dfN3y9.jpg
  - https://cdn.jsdelivr.net/gh/ShmilyXI/Gallerys@master/NoteImage/nLILmG.jpg
  - https://cdn.jsdelivr.net/gh/ShmilyXI/Gallerys@master/NoteImage/2YQ19A.jpg

  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/1.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/2.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/5.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/6.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/7.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/8.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/9.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/10.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/11.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/12.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/13.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/14.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/15.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/16.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/17.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/18.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/19.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/20.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/21.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/22.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/23.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/24.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/25.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/26.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/27.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/28.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/29.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/30.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/31.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/32.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/33.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/34.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/35.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/36.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/37.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/47.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/48.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/49.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/57.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/58.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/59.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/60.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/115.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/119 (2).jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/226.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/aeolian3_by_wlop-dbztbo1.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/Mumei wallpaper.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/Princess PSD file.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/sacrifice.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/Wake 2.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/Wake.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/10(1).jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/24(1).jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/6b8c14f8gy1fpuq755x2zj21b80rkwmn.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/6b8c14f8gy1fplscnanwqj21b80sc42q.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/6b8c14f8gy1fpclt60s7oj21b90rwjzt.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/6b8c14f8gy1fp2zdelaqjj21c70zuq8p.jpg
  # - https://cdn.jsdelivr.net/gh/ShmilyXI/CDN@v1.0.9/img/background/1s_by_wlop-dc1sdan.jpg

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
# url:链接的跳转地址
startdash:
  - { url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png }
  - { url: https://live.bilibili.com/21932206, title: Bilibil, desc: B站快乐直播, img: /img/startdash/bilibili.jpg }
  - { url: /, title: Title, desc: desc, img: /img/startdash/wangshiwu.jpg }

# your site build time or founded date
siteBuildingTime: 21/05/2019

#social  url, img PC端配置
social:
  qq: { url: https://wpa.qq.com/msgrd?v=3&uin=1262260527&site=qq&menu=yes, img: /img/social/qq.png }
  wechat: { url: /#, qrcode: /image/KWDB50.jpg, img: /img/social/wechat.png }
  github: { url: https://github.com/ShmilyXI, img: /img/social/github.png }
  zhihu: { url: https://www.zhihu.com/people/xrj-54/activities, img: /img/social/zhihu.png }
  bilibili: { url: https://space.bilibili.com/15835744, img: /img/social/bilibili.png }
  wangyiyun: { url: https://music.163.com/#/user/home?id=338969676, img: /img/social/wangyiyun.png }

#social  url, img 移动端配置
msocial:
  qq: { url: https://wpa.qq.com/msgrd?v=3&uin=1262260527&site=qq&menu=yes, fa: fa-qq, color: 25c6fe }
  github: { url: https://github.com/ShmilyXI, fa: fa-github, color: 333 }
  wechat: { url: https://www.zhihu.com/people/xrj-54/activities, fa: fa-wechat, color: 01cf0b }

donate:
  alipay: /img/custom/donate/AliPayQR.jpg
  wechatSQ: /img/custom/donate/WeChanSQ.png
  wechat: /img/custom/wechat.png

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer:
  id: 474291150
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
# https://leancloud.cn/dashboard/data.html?appid=1grSYbPmklaQJKIROx5jbYh2-gzGzoHsz#/Comment
valine: true
v_appId: 1grSYbPmklaQJKIROx5jbYh2-gzGzoHsz
v_appKey: oSS1xKti7BHYHWFXkS88uBEc
